# Generated by Django 5.2.13 on 2026-04-25 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('vin', models.CharField(blank=True, max_length=50, null=True)),
                ('plate_number', models.CharField(max_length=20)),
                ('year_produced', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('hash_passwd', models.TextField()),
                ('role', models.CharField(choices=[('client', 'Клиент'), ('master', 'Мастер'), ('manager', 'Менеджер'), ('admin', 'Администратор')], default='client', max_length=20)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status_id', models.IntegerField(blank=True, null=True)),
                ('payment_id', models.IntegerField(blank=True, null=True)),
                ('problem_desc', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_id', models.IntegerField()),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_id', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.user')),
                ('phone', models.CharField(max_length=20)),
                ('type_client_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
    ]
