# Generated by Django 5.2.13 on 2026-04-26 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_car_user_order_delete_request_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleShift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=20)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'db_table': 'schedule_shifts',
            },
        ),
    ]
