# Generated by Django 6.0.4 on 2026-04-27 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_manager_master_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleshift',
            options={'managed': False},
        ),
    ]
